permalink: /:year/:month/:day/:title.html
paginate: 5


# 作者信息
author: 
  name: holyjunhui
  email: holyjunhui@163.com
  link: https://holyjunhui.github.io/
  weibo: http://weibo.com/u/3001966001
  github: https://github.com/holyjunhui
  music: http://music.163.com/#
  linkedin: https://www.linkedin.com/in/%E4%BF%8A%E8%BE%89-%E6%9D%8E-6595a7139/

# 站点信息
title: 李俊辉的博客
description: My personal blog
url: https://holyjunhui.github.io/
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-92879162-1 
  url: holyjunhui.github.io

# disqus 设置
disqus:
  shortname: holyjunhui

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档